apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 8081 # Port di luar cluster (yang bisa diakses user)
      targetPort: 80 # Port di dalam container
  type: LoadBalancer
