name: Simple CI Check

on:
  push:
    branches:
      - development

jobs:
  basic-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Validate HTML file exists
        run: ls index.html
